name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build Go-Blog
        run: |
          go build -o go-blog main.go

      - name: Generate Static Site
        run: |
          ./go-blog generate

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Commit and Push to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          git checkout main -- public
          mv public/* .
          rm -r public
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
