name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
            repository: kaustubha-chaturvedi/expo.go
            token: ${{ secrets.pat }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
            go-version: 1.21

      - name: Build & Run Portfolio
        run: |
          go build -o expo .
          ./expo

      - name: Clone Target Repository
        run: git clone https://github.com/kaustubha-chaturvedi/kaustubha-chaturvedi.github.io.git
        env:
            TARGET_REPO_TOKEN: ${{ secrets.STATIC_REPO }}

      - name: Copy Files
        run: cp -r public/* kaustubha-chaturvedi.github.io/

      - name: Configure Git
        run: |
          cd kaustubha-chaturvedi.github.io
          git config user.email "kaustubhachaturvedi@outlook.com"
          git config user.name "kaustubha-chaturvedi"
          git config --global url.https://${{ secrets.pat }}@github.com/.insteadOf https://github.com/

      - name: Commit and Push to Target Repository
        run: |
          cd kaustubha-chaturvedi.github.io
          git add .
          git commit -m "Update GitHub Pages"
          git push origin main